package com.example.Finance_Tracker.Settings.util;

public enum SettingKey {
    AUTO_SYNC_ENABLED,
    SYNC_FREQUENCY_MINUTES,
    NOTIFICATIONS_ENABLED,
    NOTIFY_BUDGET_EXPIRY,
    NOTIFY_SPENDING_ALERTS,
    DEFAULT_BUDGET_DURATION,
    DEFAULT_CURRENCY
}