-- V1: baseline schema.
-- Mirrors the JPA entities as of this migration (Hibernate runs with ddl-auto=validate),
-- plus what Hibernate's auto-DDL never added: foreign keys to users with ON DELETE CASCADE,
-- indexes on the columns every query filters by, and CHECK constraints for enum columns.

CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE blacklisted_tokens (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token          VARCHAR(512) NOT NULL UNIQUE,
    blacklisted_at TIMESTAMP(6) NOT NULL,
    expiry         TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_blacklisted_tokens_expiry ON blacklisted_tokens (expiry);

CREATE TABLE password_reset_tokens (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token   VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    expiry  TIMESTAMP(6) NOT NULL,
    used    BOOLEAN NOT NULL
);

CREATE TABLE transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    amount           DOUBLE PRECISION NOT NULL,
    type             VARCHAR(20) NOT NULL CHECK (type IN ('INCOME', 'EXPENSE')),
    category         VARCHAR(255) NOT NULL,
    description      VARCHAR(255),
    transaction_date TIMESTAMP(6) NOT NULL,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL,
    content_hash     VARCHAR(64) NOT NULL
);
CREATE INDEX idx_transactions_user_date ON transactions (user_id, transaction_date);

CREATE TABLE budgets (
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                          BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name                             VARCHAR(255) NOT NULL,
    amount                           NUMERIC(19, 2) NOT NULL,
    spent_amount                     NUMERIC(19, 2),
    start_date                       DATE NOT NULL,
    end_date                         DATE NOT NULL,
    created_at                       TIMESTAMP(6) NOT NULL,
    updated_at                       TIMESTAMP(6) NOT NULL,
    frequency                        VARCHAR(20) NOT NULL
        CHECK (frequency IN ('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY')),
    status                           VARCHAR(20) NOT NULL
        CHECK (status IN ('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED')),
    notes                            VARCHAR(255),
    last_notified_stage              VARCHAR(20) NOT NULL
        CHECK (last_notified_stage IN ('NONE', 'FIFTY_PERCENT', 'NINETY_PERCENT', 'EXCEEDED')),
    expiry_notification_sent         BOOLEAN NOT NULL,
    nearing_expiry_notification_sent BOOLEAN NOT NULL,
    content_hash                     VARCHAR(64) NOT NULL
);
CREATE INDEX idx_budgets_user ON budgets (user_id);

CREATE TABLE notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title        VARCHAR(255) NOT NULL,
    message      VARCHAR(1000),
    type         VARCHAR(30) NOT NULL
        CHECK (type IN ('INFO', 'WARNING', 'ALERT', 'BUDGET_ALERT', 'TRANSACTION_ALERT', 'SYNC_SUCCESS')),
    read         BOOLEAN NOT NULL,
    reference_id BIGINT,
    archived     BOOLEAN NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6)
);
CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at);

CREATE TABLE user_settings (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    key        VARCHAR(50) NOT NULL
        CHECK (key IN ('AUTO_SYNC_ENABLED', 'SYNC_FREQUENCY_MINUTES', 'NOTIFICATIONS_ENABLED', 'NOTIFY_SYNC_EVENTS',
                       'NOTIFY_BUDGET_EXPIRY', 'NOTIFY_SPENDING_ALERTS', 'DEFAULT_BUDGET_DURATION', 'DEFAULT_CURRENCY')),
    value      VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_user_settings_user_key UNIQUE (user_id, key)
);
