-- V4: offline sync (GET /api/sync).
-- * deleted_transactions records every deleted transaction, so a delta sync can tell the app
--   to drop its copy. Budgets need no such table: every sync sends the complete budget list.
-- * idx_transactions_user_updated serves "transactions of a user changed since X".
CREATE TABLE deleted_transactions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    transaction_id BIGINT       NOT NULL,
    deleted_at     TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_deleted_transactions_user_deleted ON deleted_transactions (user_id, deleted_at);

CREATE INDEX idx_transactions_user_updated ON transactions (user_id, updated_at);
