-- V5: push notifications (FCM).
-- * device_tokens holds the Firebase registration token of each signed-in app install.
--   A token is unique: when another account signs in on the same phone, the row moves to that user,
--   so the previous account's notifications never reach that phone.
-- * Rows go with the user (ON DELETE CASCADE); tokens Firebase reports as gone are deleted by the server.
CREATE TABLE device_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token      VARCHAR(4096) NOT NULL UNIQUE,
    platform   VARCHAR(20)   NOT NULL,
    created_at TIMESTAMP(6)  NOT NULL,
    updated_at TIMESTAMP(6)  NOT NULL
);

CREATE INDEX idx_device_tokens_user ON device_tokens (user_id);
